<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHnD9Ekq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHnD9Ekq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHnD9Ekq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHnD9Ekq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHnD9Ekq\App_KernelDevDebugContainer([
    'container.build_hash' => 'HnD9Ekq',
    'container.build_id' => 'f599fbac',
    'container.build_time' => 1663659041,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHnD9Ekq');
