<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFm6xTSg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFm6xTSg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFm6xTSg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFm6xTSg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFm6xTSg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fm6xTSg',
    'container.build_id' => '53ddf2ef',
    'container.build_time' => 1663591325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFm6xTSg');
